### ISSUE TITLE
Adjusting your add-on to be compatible with Angular 1.8 

### ISSUE THREAD

**Issue by nilinatan** [thirdiron/primo-studio-browzine#6]
We plan to upgrade from Angular 1.6.10 to Angular 1.8 in the Primo/Primo VE November 2022 release.
This upgrade may impact your Angular customizations in Primo and Primo VE, specifically your Primo-Studio add-on.
Please make sure to adjust the customizations accordingly prior to the upgrade to ensure a smooth migration to Angular 1.8.
With the November release we will introduce in Primo Studio only add-ons that are adjustable to the Angular 1.8.

You can read more on this planned upgrade on 
https://knowledge.exlibrisgroup.com/Primo/Product_Materials/Announcements/Preparing_for_the_Upgrade_to_Angular_1.8_in_Primo%2F%2FPrimo_VE
[Adjust your customization code using the Transformer Tool](https://astexplorer.net/)
Check this [YouTube](https://youtu.be/jm2w9ghrzaU) for guidelines
Recent webinars: [EMEA/APAC ](https://youtu.be/aZ8A6aF-cFI)and [Americas/EMEA](https://youtu.be/jm2w9ghrzaU)

Please make sure to upload your adjustable add-on prior to November release 
Primo Product Team

**Comment by johnseguin** [comment]
Hi @nilinatan - John here!  Hope you are well!  Worry not - the message has gotten to us from a number of our mutual customers and we are well on our way to releasing the changes to be compatible.  Thank you very much for reaching out!

**Comment by jeffnm** [comment]
I'm glad to hear that this update is coming. Is it still on schedule to be released prior to the Primo VE November release?

This add-on is the one bit of customization code that has not yet been updated yet in our customization package.

**Comment by johnseguin** [comment]
@jeffnm We updated our code several weeks ago which should produce a seamless update on your end if you are referencing our cloud hosted main script with no additional changes needed.  If you are still seeing issues do drop us a line at support@thirdiron.com so we can investigate.  Thank you!

**Comment by jeffnm** [comment]
@johnseguin Thanks for that information. I've submitted a ticket with what we're seeing that made me think it wasn't updated yet. It may not be an issue at all, but figured I should run it by you all.
